pretraining: False # ture: instantiate and train an embedding model
embedding_model_path: #
task: ["info.density"]
MOF_id: "info.cifname"
label_path: "../../data/application_v2.csv"
embedding_path: wandb/offline-run-20230704_170040-8yeh8hgo/tmp/embedding_dv.csv # same as gensim storage path
train_frac: 0.8
valid_frac: 0.1
test_frac: 0.1
batch_size: 256
num_workers: 6
seed: 2234