task: ["outputs.pbe.bandgap"]
MOF_id: "qmof_id"
label_path: "../../data/qmof-data.csv"
embedding_path: wandb/offline-run-20230320_165953-5nnlomfl/tmp/embedding_dv.csv # same as gensim storage path
train_frac: 0.8
valid_frac: 0.1
test_frac: 0.1
batch_size: 1024
num_workers: 6
device: "cpu"
seed: 2234