pretraining: True # ture: instantiate and train an embedding model
embedding_model_path: #../../data/embedding_model/embedding_model.pt
task: ["outputs.pbe.bandgap"] #["outputs.CO2-henry_coefficient-mol--kg--Pa"]
MOF_id: "info.qmof_id"
label_path: "../../data/md-qmof.csv"
embedding_path: #wandb/offline-run-20230705_191136-29xt07cq/tmp/embedding_dv.csv #wandb/offline-run-20230320_165953-5nnlomfl/tmp/embedding_dv.csv #24 # same as gensim storage path
train_frac: 0.8
valid_frac: 0.1
test_frac: 0.1
batch_size: 512
num_workers: 6
seed: 2234
