task: ["outputs.pbe.bandgap"] #["outputs.CO2-henry_coefficient-mol--kg--Pa"]
MOF_id: "qmof_id"
label_path: "../../data/qmof-data.csv"
embedding_path: ../../data/fine-tune-embedding/bg1024-133.csv #wandb/offline-run-20230321_114831-3kwsegz5/tmp/embedding_dv.csv #wandb/offline-run-20230320_165953-5nnlomfl/tmp/embedding_dv.csv #24 # same as gensim storage path
train_frac: 0.8
valid_frac: 0.1
test_frac: 0.1
batch_size: 512
num_workers: 6
seed: 2234

#offline-run-20230320_165953-5nnlomfl/tmp/embedding-outputs.pbe.bandgap.csv