pretraining: true
embedding_model_path: #../../data/embedding_model/embedding_model.pt
task: ["logKH_CO2"]
MOF_id: "cif.label"
label_path: "../../data/data.csv"
embedding_path: wandb/offline-run-20230511_222802-32gyt2yh/tmp/embedding_dv.csv # same as gensim storage path
train_frac: 0.8
valid_frac: 0.1
test_frac: 0.1
batch_size: 256
num_workers: 6
seed: 2234