defaults:
  - _self_
  - data: 
    - data.yaml
    - nn.yaml
  - model: 
    - gensim.yaml 
    - sklearn.yaml
  - trainer:
    - default.yaml
  - sweep:
    - sklearn.yaml

logger:
  project: mof2vec
  entity: xiaoqiz
  mode: online
  tags: co2 uptake, rsm, xgb

seed: 1234
load_model: false
model_checkpoint: null
sweep: false