defaults:
  - _self_
  - mof2vec_data: 
    - data.yaml
  - mof2vec_model:
    - gensim.yaml
  - doc2label_data: 
    - default.yaml 
  - doc2label_model:
    - ensemble.yaml
  - sweep:
    - mof2vec.yaml

logger:
  project: # wandb project
  entity: # wandb entity
  mode: # offline or online
  tags: 

seed: 5432
sweep: false
mode: workflow # available choices: mof2vec, doc2label, workflow