defaults:
  - _self_
  - mof2vec_data: 
    - data.yaml
  - mof2vec_model:
    - gensim.yaml
  - doc2label_data: 
    - default.yaml 
  - doc2label_model:
    - ensemble.yaml
  - sweep:
    - mof2vec.yaml

logger:
  project: mof2vec
  entity: xiaoqiz
  mode: offline
  tags: 

seed: 5432
sweep: false
mode: mof2vec # available choices: mof2vec, doc2label, workflow