defaults:
  - _self_
  - data: 
    - data.yaml
    - nn.yaml
  - model: 
    - gensim.yaml 
    - nn.yaml
  - trainer:
    - default.yaml
  - unsupervised_sweep: 
    - gensim.yaml
  - supervised_sweep: 
    - nn.yaml

logger:
  project: mof2vec
  entity: xiaoqiz
  mode: offline
  tags:

seed: 1234
load_model: false
model_checkpoint: null
sweep: false