defaults:
  - _self_
  - data: 
    - data.yaml
    - nn.yaml
  - model: 
    - gensim.yaml 
    - nn.yaml
  - sweep: gensim.yaml

logger:
  project: mof2vec
  entity: xiaoqiz
  mode: online
  tags:

seed: 1234
load_model: false
model_checkpoint: null