nn:
  _target_: mofgraph2vec.model.nn_lightning.VecLightningModule
  model: "nn"
  input_dim: 32 # same as config.model.gensim.vector_size
  output_dim: 1
  fcnn_n_layers: 3
  fcnn_hidden_size: 128
  fcnn_activation: "relu"
  dropout: null
  loss: "mse"
  lr: 1e-4

  batch_size: 64
  max_epochs: 100
