nn:
  _target_: mofgraph2vec.model.vecnn.VecModel
  input_dim: 53 # same as config.model.gensim.vector_size
  output_dim: 1
  fcnn_n_layers: 5
  fcnn_hidden_size: 128
  fcnn_activation: "relu"
  dropout: null
  
loss: "mse"
lr: 1e-4
patience: 6
checkpoint: true
