nn:
  _target_: mofgraph2vec.model.vecnn.VecModel
  input_dim: 512 # same as config.model.gensim.vector_size
  output_dim: 1
  fcnn_n_layers: 5
  fcnn_hidden_size: 600
  fcnn_activation: "relu"
  dropout: 0.2
  
loss: "mse"
lr: 0.01
patience: 6
checkpoint: true
random_state: 2234
