nn:
  _target_: mofgraph2vec.model.vecnn.VecModel
  input_dim: 256 # same as config.model.gensim.vector_size
  output_dim: 1
  fcnn_n_layers: 2
  fcnn_hidden_size: 70
  fcnn_activation: "relu"
  dropout: 0.2
  
loss: "mse"
lr: 0.3
patience: 6
checkpoint: true
random_state: 2234
