#_target_: mofgraph2vec.model.regressor.Regressor
n_estimators: 450
max_depth: 6
gamma: 
reg_alpha: 0.5
reg_lambda: 
subsample: 
colsample_bytree: 
min_child_weight: 2
learning_rate: 0.1
n_jobs: -2
random_state: 2234
