#_target_: mofgraph2vec.model.regressor.Regressor
n_estimators: 100
max_depth: 5
gamma: #1
reg_alpha: #
reg_lambda: #9
subsample: #0.7 
colsample_bytree: #0.7
min_child_weight: #5
learning_rate: 0.1
n_jobs: -2
random_state: 2234
