#_target_: mofgraph2vec.model.regressor.Regressor
n_estimators: 100
max_depth: 3
gamma: 
reg_alpha: 
reg_lambda: 
subsample: 
colsample_bytree: 
min_child_weight: 
learning_rate: 0.1
n_jobs: -2
random_state: 2234
