#_target_: mofgraph2vec.model.regressor.Regressor
n_estimators: 500
max_depth: 5
gamma: 
reg_alpha: 
reg_lambda: 0.8
subsample: 
colsample_bytree: 
min_child_weight: 
learning_rate: 0.1
max_delta_step: 2
n_jobs: -2
random_state: 2234
