data:
  _target_: mofgraph2vec.featurize.mof2doc.MOF2doc
  cif_path: ["../../data/cifs/application_ori/"]
  embed_label: True
  label_path: "../../data/application_v2.csv"
  labels_to_embed: [
    "info.density",
    "outputs.pbe.bandgap",
    #"outputs.pbe.energy_elec",
    "outputs.pbe.energy_total",
    "outputs.logKH_CO2",
    "outputs.logKH_CH4",
    "outputs.assigned_T_decomp",
    "info.pld",
    "info.lcd",
    #"info.volume",
    "outputs.pure_uptake_CO2_298.00_15000", 
    "outputs.pure_uptake_CO2_298.00_1600000",
    "outputs.pure_uptake_methane_298.00_580000", 
    "outputs.pure_uptake_methane_298.00_6500000",
    "outputs.pure_CO2_widomHOA", 
    "outputs.pure_methane_widomHOA",
    #"info.r_factor"
  ]
  id_column: "info.cifname"
  wl_step: 2
  n_components: 20
  use_hash: false
  writing_style: "paragraph"
  composition: False
  mode: all # all, scaffold, nodes, linker
  embed_cif: false