data:
  _target_: mofgraph2vec.featurize.mof2doc.MOF2doc
  cif_path: # 
  embed_label: True
  label_path: #
  descriptors_to_embed: # 
  category_to_embed: #
  tags_to_embed: #
  id_column: #
  wl_step: 2
  n_components: 20
  use_hash: false
  writing_style: "paragraph"
  composition: False
  mode: all # all, scaffold, nodes, linker
  embed_cif: false