data:
  _target_: mofgraph2vec.featurize.mof2doc.MOF2doc
  cif_path: ["../../data/cifs/md_1990/", "../../data/cifs/md_1990_2000/", "../../data/cifs/md_2000_2005/", "../../data/cifs/md_2006/", "../../data/cifs/md_2007/", "../../data/cifs/md_2008/", "../../data/cifs/md_2009/", "../../data/cifs/md_2010/", "../../data/cifs/md_2011/", "../../data/cifs/md_2012/", "../../data/cifs/md_2013/", "../../data/cifs/md_2014/", "../../data/cifs/md_2015/", "../../data/cifs/md_2016/"] #, "../../data/cifs/md_2017/"]
  embed_label: False
  label_path: "../../data/md-core.csv"
  labels_to_embed: ["info.density", "outputs.logKH_CO2", "outputs.logKH_CH4", "outputs.pure_uptake_CO2_298.00_15000", "outputs.pure_uptake_CO2_298.00_1600000", "outputs.pure_uptake_methane_298.00_580000", "outputs.pure_uptake_methane_298.00_6500000"]
  id_column: "info.name"
  wl_step: 2
  n_components: 20
  use_hash: false
  writing_style: "paragraph"
  composition: False
  mode: all # all, scaffold, nodes, linker
  embed_cif: false