data:
  _target_: mofgraph2vec.featurize.mof2doc.MOF2doc
  cif_path: ["../../data/cifs/rsm/"] #, "../../data/cifs/qmof/", "../../data/cifs/hMOF/"]
  subsample: null
  wl_step: 4
  n_components: 20
  use_hash: false
  writing_style: "paragraph"
  composition: true
  mode: scaffold # all, nodes, linker
  embed_cif: false