data:
  _target_: mofgraph2vec.featurize.mof2doc.MOF2doc
  cif_path: ["../../data/cifs/qmof/"] 
  embed_label: True
  label_path: "../../data/qmof-data.csv"
  descriptors_to_embed: ["info.pld", "info.lcd", "info.density"] 
  category_to_embed: []
  tags_to_embed: [] #"xq.ch4_logkh", "xq.ch4_uptake_580000", "xq.ch4_uptake_6500000"] #["xq.ch4_uptake_6500000"] #["xq.ch4_logkh", "xq.ch4_uptake_6500000"]
  id_column: "qmof_id"
  wl_step: 2
  n_components: 20
  use_hash: false
  writing_style: "paragraph"
  composition: False
  mode: all # all, scaffold, nodes, linker
  embed_cif: false